# -*- coding: utf-8 -*-
"""analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KiOus6W28rAUPW029B-GtnXtLRWe9zSu
"""

import pandas as pd
from datetime import date

# ============================================================
# TASK 3: ANALYTICAL THINKING
# ============================================================

# Load raw dataset as strings so that placeholder values
# are preserved before cleaning.
transactions = pd.read_csv(
    "transactions.csv",
    dtype=str,
    keep_default_na=False
)

# ------------------------------------------------------------
# CLEAN DATA FOR ANALYSIS
# ------------------------------------------------------------

null_like_tokens = {
    "",
    "nan",
    "null",
    "n/a",
    "#n/a",
    "missing",
    "-",
    "?"
}

# Remove duplicate transaction IDs
clean = transactions.drop_duplicates(
    subset="transaction_id",
    keep="first"
).copy()

# Remove invalid consumer IDs
valid_consumer_id = ~(
    clean["consumer_id"]
    .str.strip()
    .str.lower()
    .isin(null_like_tokens)
)

clean = clean[valid_consumer_id].copy()

# Parse dates and amounts safely
clean["transaction_date_parsed"] = pd.to_datetime(
    clean["transaction_date"],
    format="%Y-%m-%d",
    errors="coerce"
)

clean["amount_numeric"] = pd.to_numeric(
    clean["amount"],
    errors="coerce"
)

# Keep only valid transaction types
clean = clean[
    clean["transaction_type"].isin(["DR", "CR"])
].copy()

# Remove invalid dates and amounts
clean = clean[
    clean["transaction_date_parsed"].notna()
    & clean["amount_numeric"].notna()
].copy()

# Remove future-dated transactions
today = pd.Timestamp(date.today())

clean = clean[
    clean["transaction_date_parsed"] <= today
].copy()

# Remove DR/CR sign inconsistencies
sign_consistent = (
    (
        (clean["transaction_type"] == "DR")
        & (clean["amount_numeric"] < 0)
    )
    |
    (
        (clean["transaction_type"] == "CR")
        & (clean["amount_numeric"] > 0)
    )
)

clean = clean[sign_consistent].copy()

print("\n==============================================")
print("CLEAN DATASET USED FOR TASK 3")
print("==============================================")
print(f"Rows used: {len(clean)}")
print(f"Consumers used: {clean['consumer_id'].nunique()}")


# ============================================================
# 3A: CONSUMER BEHAVIOUR SEGMENTATION
# ============================================================

consumer_features = (
    clean
    .groupby("consumer_id")
    .agg(
        transaction_count=("transaction_id", "size"),

        total_debit=(
            "amount_numeric",
            lambda x: abs(x[x < 0]).sum()
        ),

        total_credit=(
            "amount_numeric",
            lambda x: x[x > 0].sum()
        ),

        average_transaction=(
            "amount_numeric",
            lambda x: x.abs().mean()
        )
    )
    .reset_index()
)

# Median thresholds for the 2x2 segmentation
median_frequency = consumer_features[
    "transaction_count"
].median()

median_amount = consumer_features[
    "average_transaction"
].median()


# ------------------------------------------------------------
# Identify sparse / extreme consumer profiles using IQR
# ------------------------------------------------------------

def iqr_bounds(series):
    q1 = series.quantile(0.25)
    q3 = series.quantile(0.75)

    iqr = q3 - q1

    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr

    return lower, upper


freq_lower, freq_upper = iqr_bounds(
    consumer_features["transaction_count"]
)

amount_lower, amount_upper = iqr_bounds(
    consumer_features["average_transaction"]
)


def assign_segment(row):

    # Separate unusually sparse or extreme profiles first
    if (
        row["transaction_count"] < freq_lower
        or row["transaction_count"] > freq_upper
        or row["average_transaction"] < amount_lower
        or row["average_transaction"] > amount_upper
    ):
        return "Sparse / Outlier Profile"

    # 2x2 frequency-value segmentation
    if (
        row["transaction_count"] >= median_frequency
        and row["average_transaction"] >= median_amount
    ):
        return "High Frequency - High Amount"

    if (
        row["transaction_count"] < median_frequency
        and row["average_transaction"] >= median_amount
    ):
        return "Low Frequency - High Amount"

    if (
        row["transaction_count"] >= median_frequency
        and row["average_transaction"] < median_amount
    ):
        return "High Frequency - Low Amount"

    return "Low Frequency - Low Amount"


consumer_features["segment"] = consumer_features.apply(
    assign_segment,
    axis=1
)

segment_summary = (
    consumer_features["segment"]
    .value_counts()
    .rename_axis("segment")
    .reset_index(name="consumer_count")
)

print("\n==============================================")
print("3A: CONSUMER BEHAVIOUR SEGMENTATION")
print("==============================================")

print(f"Median transaction frequency: {median_frequency:.2f}")
print(f"Median average transaction value: {median_amount:.2f}")

print("\nSegment distribution:")
print(segment_summary)

print(
    "\nApproach: Consumers are segmented using two observable "
    "behavioural dimensions: transaction frequency and average "
    "transaction value. Median values provide data-driven cut-offs "
    "for a 2x2 high/low matrix, while unusually sparse or extreme "
    "profiles are separated using the 1.5xIQR rule."
)

print(
    "\nWhy it matters: The segments distinguish consumers who transact "
    "frequently or infrequently and at relatively high or low values. "
    "In a credit-scoring context, these represent different behavioural "
    "profiles and can support differentiated risk assessment without "
    "assuming that any one segment is automatically creditworthy."
)


# ============================================================
# 3B: OUTLIER DETECTION
# ============================================================

outlier_features = [
    "transaction_count",
    "total_debit",
    "total_credit",
    "average_transaction"
]

for feature in outlier_features:

    lower, upper = iqr_bounds(
        consumer_features[feature]
    )

    consumer_features[
        f"outlier_{feature}"
    ] = (
        (consumer_features[feature] < lower)
        |
        (consumer_features[feature] > upper)
    )


outlier_columns = [
    f"outlier_{feature}"
    for feature in outlier_features
]

consumer_features["any_outlier"] = (
    consumer_features[outlier_columns]
    .any(axis=1)
)

outlier_consumers = consumer_features[
    consumer_features["any_outlier"]
].copy()


print("\n==============================================")
print("3B: OUTLIER DETECTION")
print("==============================================")

print(
    f"Number of behavioural outliers: "
    f"{len(outlier_consumers)}"
)

print(
    outlier_consumers[
        [
            "consumer_id",
            "transaction_count",
            "total_debit",
            "total_credit",
            "average_transaction"
        ]
        + outlier_columns
    ]
)

print(
    "\nApproach: Behavioural outliers are detected at the consumer "
    "level using the 1.5xIQR rule across transaction frequency, "
    "total debit volume, total credit volume, and average transaction "
    "value. Invalid consumer identifiers are removed before this step "
    "so that data-quality errors are not mistaken for unusual behaviour."
)

print(
    "\nWhy it matters: IQR is resistant to skew and does not require "
    "transaction behaviour to follow a normal distribution. Flagged "
    "consumers should be reviewed further rather than automatically "
    "classified as fraudulent or risky."
)


# ============================================================
# 3C: ADDITIONAL INSIGHT — MERCHANT ACTIVITY SPIKES
# ============================================================

merchant_data = clean.copy()

# Merchant/category is the middle element of narrations such as:
# NEFT/JIO/REF6183

merchant_data["merchant"] = (
    merchant_data["full_narration"]
    .str.split("/")
    .str[1]
)

merchant_data = merchant_data[
    merchant_data["merchant"].notna()
    & merchant_data["merchant"].str.strip().ne("")
].copy()

# Restrict seasonality-style analysis to 2024,
# because the supplied valid transaction history is primarily 2024.
merchant_data = merchant_data[
    merchant_data["transaction_date_parsed"].dt.year == 2024
].copy()

merchant_data["month"] = (
    merchant_data["transaction_date_parsed"]
    .dt.to_period("M")
    .astype(str)
)

# Only assess merchants/categories with enough observations
merchant_totals = (
    merchant_data
    .groupby("merchant")
    .size()
    .reset_index(name="total_transactions")
)

active_merchants = merchant_totals[
    merchant_totals["total_transactions"] >= 20
]["merchant"]


merchant_monthly = (
    merchant_data[
        merchant_data["merchant"].isin(active_merchants)
    ]
    .groupby(
        ["merchant", "month"]
    )
    .size()
    .reset_index(name="transaction_count")
)

# Add months in which a merchant had zero transactions
all_months = [
    f"2024-{month:02d}"
    for month in range(1, 13)
]

merchant_month_index = pd.MultiIndex.from_product(
    [
        active_merchants,
        all_months
    ],
    names=["merchant", "month"]
)

merchant_monthly_complete = (
    merchant_monthly
    .set_index(["merchant", "month"])
    .reindex(
        merchant_month_index,
        fill_value=0
    )
    .reset_index()
)


seasonality = (
    merchant_monthly_complete
    .groupby("merchant")
    .agg(
        total_transactions=(
            "transaction_count",
            "sum"
        ),
        max_monthly_transactions=(
            "transaction_count",
            "max"
        ),
        average_monthly_transactions=(
            "transaction_count",
            "mean"
        )
    )
    .reset_index()
)

seasonality["peak_to_average_ratio"] = (
    seasonality["max_monthly_transactions"]
    /
    seasonality["average_monthly_transactions"]
)


# Identify peak month for each merchant
peak_rows = (
    merchant_monthly_complete
    .sort_values(
        "transaction_count",
        ascending=False
    )
    .drop_duplicates(
        subset="merchant"
    )
    [["merchant", "month", "transaction_count"]]
    .rename(
        columns={
            "month": "peak_month",
            "transaction_count": "peak_transactions"
        }
    )
)

seasonality = seasonality.merge(
    peak_rows,
    on="merchant",
    how="left"
)

seasonality = seasonality.sort_values(
    "peak_to_average_ratio",
    ascending=False
)

# Merchants whose peak month is at least twice
# their average monthly transaction frequency
strong_spikes = seasonality[
    seasonality["peak_to_average_ratio"] >= 2
].copy()


print("\n==============================================")
print("3C: MERCHANT-LEVEL MONTHLY ACTIVITY SPIKES")
print("==============================================")

print(
    f"Active merchants/categories with >=2x peak-to-average activity: "
    f"{len(strong_spikes)}"
)

print(
    strong_spikes[
        [
            "merchant",
            "peak_month",
            "peak_transactions",
            "average_monthly_transactions",
            "peak_to_average_ratio"
        ]
    ].to_string(index=False)
)

if len(strong_spikes) > 0:

    strongest = strong_spikes.iloc[0]

    print(
        f"\nStrongest example: {strongest['merchant']} "
        f"recorded {int(strongest['peak_transactions'])} transactions "
        f"in {strongest['peak_month']}, compared with an average of "
        f"{strongest['average_monthly_transactions']:.2f} per month "
        f"({strongest['peak_to_average_ratio']:.2f}x the monthly average)."
    )

print(
    "\nInsight: Several active merchants show concentrated monthly "
    "transaction spikes, suggesting that merchant-level spending can "
    "change sharply even when overall consumer behaviour appears stable. "
    "A product team could use such relative spikes for budgeting nudges, "
    "merchant-specific offers, or unusual-spending alerts."
)

print(
    "\nCaution: Because the dataset covers only one calendar year, "
    "these patterns should be described as monthly concentration or "
    "seasonal-looking spikes rather than proof of recurring seasonality."
)


# ============================================================
# SAVE ANALYSIS OUTPUTS
# ============================================================

consumer_features.to_csv(
    "consumer_segments.csv",
    index=False
)

outlier_consumers.to_csv(
    "consumer_outliers.csv",
    index=False
)

seasonality.to_csv(
    "merchant_monthly_patterns.csv",
    index=False
)

print("\n==============================================")
print("TASK 3 COMPLETE")
print("==============================================")