# -*- coding: utf-8 -*-
"""Task 1: EDA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KiOus6W28rAUPW029B-GtnXtLRWe9zSu
"""

!pip install openpyxl

import pandas as pd

# -----------------------------
# TASK 1: DATA EXPLORATION
# -----------------------------

# Load dataset
transactions = pd.read_csv("transactions.csv")

print("\n========== BASIC DATASET INFORMATION ==========\n")

print("First 5 rows:")
print(transactions.head())

print("\nDataset structure:")
transactions.info()

print("\nDataset dimensions:")
print(f"Rows: {transactions.shape[0]}")
print(f"Columns: {transactions.shape[1]}")

print("\nMissing values by column:")
print(transactions.isna().sum())

print("\nGeneral summary:")
print(transactions.describe(include="all"))


# -----------------------------
# TOTAL ROWS AND UNIQUE CONSUMERS
# -----------------------------

total_rows = len(transactions)
unique_consumers = transactions["consumer_id"].nunique()

print("\n========== DATASET SIZE ==========\n")
print(f"Total rows: {total_rows}")
print(f"Unique consumers: {unique_consumers}")


# -----------------------------
# DATE RANGE
# -----------------------------

# Preserve original transaction_date and create a parsed version
transactions["transaction_date_parsed"] = pd.to_datetime(
    transactions["transaction_date"],
    errors="coerce"
)

min_date = transactions["transaction_date_parsed"].min()
max_date = transactions["transaction_date_parsed"].max()

print("\n========== DATE RANGE ==========\n")
print(f"Minimum date: {min_date}")
print(f"Maximum date: {max_date}")


# -----------------------------
# TRANSACTION MODE DISTRIBUTION
# -----------------------------

mode_distribution = (
    transactions["transaction_mode"]
    .value_counts(dropna=False)
    .rename_axis("transaction_mode")
    .reset_index(name="transaction_count")
)

mode_distribution["percentage"] = (
    mode_distribution["transaction_count"]
    / total_rows
    * 100
).round(2)

print("\n========== TRANSACTION MODE DISTRIBUTION ==========\n")
print(mode_distribution)


# -----------------------------
# TRANSACTION TYPE DISTRIBUTION
# -----------------------------

type_distribution = (
    transactions["transaction_type"]
    .value_counts(dropna=False)
    .rename_axis("transaction_type")
    .reset_index(name="transaction_count")
)

type_distribution["percentage"] = (
    type_distribution["transaction_count"]
    / total_rows
    * 100
).round(2)

print("\n========== TRANSACTION TYPE DISTRIBUTION ==========\n")
print(type_distribution)


# -----------------------------
# AMOUNT CLEANING FOR ANALYSIS
# -----------------------------

# Keep the original amount column unchanged.
# Invalid values are converted to NaN only in amount_numeric.
transactions["amount_numeric"] = pd.to_numeric(
    transactions["amount"],
    errors="coerce"
)

invalid_amounts = transactions[
    transactions["amount_numeric"].isna()
][["transaction_id", "amount"]]

print("\n========== INVALID AMOUNT VALUES ==========\n")
print(f"Number of invalid amounts: {len(invalid_amounts)}")
print(invalid_amounts)


# -----------------------------
# DEBIT VS CREDIT SUMMARY
# -----------------------------

# Only valid DR and CR transactions are included in monetary summaries.
valid_types = transactions[
    transactions["transaction_type"].isin(["DR", "CR"])
    & transactions["amount_numeric"].notna()
].copy()

type_summary = (
    valid_types
    .groupby("transaction_type")
    .agg(
        transaction_count=("transaction_id", "size"),
        total_amount=("amount_numeric", lambda x: x.abs().sum())
    )
    .reset_index()
)

type_summary["fraction_of_total_amount"] = (
    type_summary["total_amount"]
    / type_summary["total_amount"].sum()
)

type_summary["percentage_of_total_amount"] = (
    type_summary["fraction_of_total_amount"]
    * 100
).round(2)

print("\n========== DEBIT VS CREDIT SUMMARY ==========\n")
print(type_summary)


# -----------------------------
# TOP 5 CONSUMERS BY DEBIT VOLUME
# -----------------------------

top5_debit_consumers = (
    transactions[
        (transactions["transaction_type"] == "DR")
        & transactions["amount_numeric"].notna()
    ]
    .groupby("consumer_id")
    .agg(
        total_debit_volume=("amount_numeric", lambda x: x.abs().sum()),
        transaction_count=("transaction_id", "size")
    )
    .reset_index()
    .sort_values(
        "total_debit_volume",
        ascending=False
    )
    .head(5)
)

print("\n========== TOP 5 CONSUMERS BY DEBIT VOLUME ==========\n")
print(top5_debit_consumers)


# -----------------------------
# BASIC AMOUNT EDA
# -----------------------------

amount_summary = pd.DataFrame({
    "mean_amount": [transactions["amount_numeric"].mean()],
    "median_amount": [transactions["amount_numeric"].median()],
    "minimum_amount": [transactions["amount_numeric"].min()],
    "maximum_amount": [transactions["amount_numeric"].max()],
    "valid_amount_count": [transactions["amount_numeric"].notna().sum()],
    "invalid_amount_count": [transactions["amount_numeric"].isna().sum()]
})

print("\n========== AMOUNT SUMMARY ==========\n")
print(amount_summary)


# -----------------------------
# CONSUMER ACTIVITY EDA
# -----------------------------

consumer_activity = (
    transactions
    .groupby("consumer_id")
    .size()
    .reset_index(name="transaction_count")
    .sort_values("transaction_count", ascending=False)
)

print("\n========== CONSUMER ACTIVITY SUMMARY ==========\n")
print(consumer_activity["transaction_count"].describe())


# -----------------------------
# MONTHLY TRANSACTION ACTIVITY
# -----------------------------

transactions["month"] = (
    transactions["transaction_date_parsed"]
    .dt.to_period("M")
    .astype(str)
)

monthly_activity = (
    transactions
    .groupby("month")
    .size()
    .reset_index(name="transaction_count")
    .sort_values("month")
)

print("\n========== MONTHLY TRANSACTION ACTIVITY ==========\n")
print(monthly_activity)


# -----------------------------
# SAVE OUTPUTS TO ONE EXCEL WORKBOOK
# -----------------------------

with pd.ExcelWriter("exploration_results.xlsx", engine="openpyxl") as writer:
    mode_distribution.to_excel(
        writer,
        sheet_name="Mode Distribution",
        index=False
    )

    type_distribution.to_excel(
        writer,
        sheet_name="Type Distribution",
        index=False
    )

    type_summary.to_excel(
        writer,
        sheet_name="Debit Credit Summary",
        index=False
    )

    top5_debit_consumers.to_excel(
        writer,
        sheet_name="Top 5 Debit Consumers",
        index=False
    )

    amount_summary.to_excel(
        writer,
        sheet_name="Amount Summary",
        index=False
    )

    consumer_activity.to_excel(
        writer,
        sheet_name="Consumer Activity",
        index=False
    )

    monthly_activity.to_excel(
        writer,
        sheet_name="Monthly Activity",
        index=False
    )

    invalid_amounts.to_excel(
        writer,
        sheet_name="Invalid Amounts",
        index=False
    )

print("\nTask 1 exploration complete.")
print("Results saved to exploration_results.xlsx")