# -*- coding: utf-8 -*-
"""validate

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KiOus6W28rAUPW029B-GtnXtLRWe9zSu
"""

import pandas as pd
import json
from datetime import date

# -----------------------------
# TASK 2: VALIDATION CHECKS
# -----------------------------

# Preserve all raw values as strings.
# keep_default_na=False prevents pandas from automatically converting
# values such as "NaN", "N/A", and "null" into missing values.
transactions = pd.read_csv(
    "transactions.csv",
    dtype=str,
    keep_default_na=False
)

validation_results = []


# -----------------------------
# HELPER FUNCTION
# -----------------------------

def add_result(check_id, name, affected_rows):
    """
    Adds one validation result to the final report.
    """

    validation_results.append({
        "check_id": check_id,
        "name": name,
        "status": "FAIL" if len(affected_rows) > 0 else "PASS",
        "affected_rows": len(affected_rows),
        "sample_ids": (
            affected_rows["transaction_id"]
            .head(3)
            .tolist()
        )
    })


# -----------------------------
# V-01: DUPLICATE TRANSACTION IDs
# -----------------------------

duplicate_rows = transactions[
    transactions["transaction_id"].duplicated(keep=False)
]

add_result(
    "V-01",
    "Duplicate transaction IDs",
    duplicate_rows
)


# -----------------------------
# V-02: DATE PARSEABILITY
# -----------------------------

parsed_dates = pd.to_datetime(
    transactions["transaction_date"],
    format="%Y-%m-%d",
    errors="coerce"
)

invalid_date_rows = transactions[
    parsed_dates.isna()
]

add_result(
    "V-02",
    "Date parseability",
    invalid_date_rows
)


# -----------------------------
# V-03: AMOUNT NUMERIC
# -----------------------------

amount_numeric = pd.to_numeric(
    transactions["amount"],
    errors="coerce"
)

invalid_amount_rows = transactions[
    amount_numeric.isna()
]

add_result(
    "V-03",
    "Amount numeric",
    invalid_amount_rows
)


# -----------------------------
# V-04: SIGN-TYPE CONSISTENCY
# -----------------------------

sign_mismatch = transactions[
    amount_numeric.notna()
    & (
        (
            (transactions["transaction_type"] == "DR")
            & (amount_numeric >= 0)
        )
        |
        (
            (transactions["transaction_type"] == "CR")
            & (amount_numeric <= 0)
        )
    )
]

add_result(
    "V-04",
    "Sign-type consistency",
    sign_mismatch
)


# -----------------------------
# V-05: FUTURE DATES
# -----------------------------

today = pd.Timestamp(date.today())

future_date_rows = transactions[
    parsed_dates.notna()
    & (parsed_dates > today)
]

add_result(
    "V-05",
    "Future dates",
    future_date_rows
)


# -----------------------------
# V-06: EMPTY NARRATION
# -----------------------------

empty_narration_rows = transactions[
    transactions["full_narration"]
    .str.strip()
    .eq("")
]

add_result(
    "V-06",
    "Empty narration",
    empty_narration_rows
)


# -----------------------------
# V-07: NULL-LIKE TOKENS
# -----------------------------

null_like_tokens = {
    "nan",
    "null",
    "n/a",
    "missing",
    "-",
    "?"
}

# Convert every cell to stripped lowercase text.
normalised = transactions.apply(
    lambda column: column.astype(str).str.strip().str.lower()
)

# A cell fails if it contains one of the specified placeholder
# tokens or is a whitespace-only / empty string.
null_like_mask = normalised.apply(
    lambda column:
        column.isin(null_like_tokens)
        | column.eq("")
)

# Flag a row if ANY column contains a null-like token.
null_like_rows = transactions[
    null_like_mask.any(axis=1)
]

add_result(
    "V-07",
    "Null-like tokens",
    null_like_rows
)


# -----------------------------
# PRINT VALIDATION RESULTS
# -----------------------------

print("\n========== VALIDATION REPORT ==========\n")

for result in validation_results:
    print(
        f"{result['check_id']} | "
        f"{result['name']} | "
        f"{result['status']} | "
        f"Affected rows: {result['affected_rows']} | "
        f"Sample IDs: {result['sample_ids']}"
    )


# -----------------------------
# SAVE JSON REPORT
# -----------------------------

with open(
    "validation_report.json",
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        validation_results,
        file,
        indent=4
    )

print("\nValidation complete.")
print("Report saved to validation_report.json")